select
    game_id,
    season,
    season_type,
    week,
    game_date,
    home_team,
    away_team,
    home_coach,
    away_coach,
    home_score,
    away_score,
    winner,
    scrimmage_plays,
    home_fourth_downs,
    home_go_attempts,
    away_fourth_downs,
    away_go_attempts
from {{ source('gold', 'game_summary') }}
