select
    {{ dbt.concat(["game_id", "'-'", "cast(play_id as " ~ dbt.type_string() ~ ")"]) }} as play_key,
    game_id,
    play_id,
    season,
    season_type,
    week,
    game_date,
    posteam as team,
    defteam as opponent,
    coach,
    qtr,
    ydstogo,
    yardline_100,
    game_seconds_remaining,
    score_differential,
    wp,
    decision,
    outcome,
    converted,
    p_convert,
    p_field_goal,
    ev_go,
    ev_punt,
    ev_field_goal,
    recommendation,
    go_advantage,
    expected_points_lost,
    followed_model,
    is_neutral_situation
from {{ source('gold', 'fourth_down_scored') }}
