-- 02_database_and_roles.sql
-- Run as ACCOUNTADMIN (or split between SYSADMIN for objects and SECURITYADMIN for grants).
--
-- Schemas
--   ICEBERG_RAW  Iceberg tables read from Databricks Unity Catalog (primary path)
--   ICEBERG      upper-case views over ICEBERG_RAW
--   SYNCED       native tables loaded by scripts/sync_to_snowflake.py (fallback path)
--   STAGING      dbt staging views
--   MARTS        dbt marts
--   APP          UDF, model stage, weekly summary, stream/task, Streamlit app
--
-- Roles (least privilege; each role gets only what its workload needs)
--   GRIDIRON_ADMIN        owns the database and runs the setup scripts
--   GRIDIRON_LOADER       fallback sync: writes SYNCED only
--   GRIDIRON_TRANSFORMER  dbt: reads ICEBERG / SYNCED, builds STAGING and MARTS
--   GRIDIRON_READER       Streamlit and analysts: reads MARTS and APP, calls the UDF

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS GRIDIRON_ADMIN;
CREATE ROLE IF NOT EXISTS GRIDIRON_LOADER;
CREATE ROLE IF NOT EXISTS GRIDIRON_TRANSFORMER;
CREATE ROLE IF NOT EXISTS GRIDIRON_READER;

GRANT ROLE GRIDIRON_READER TO ROLE GRIDIRON_TRANSFORMER;
GRANT ROLE GRIDIRON_TRANSFORMER TO ROLE GRIDIRON_ADMIN;
GRANT ROLE GRIDIRON_LOADER TO ROLE GRIDIRON_ADMIN;
GRANT ROLE GRIDIRON_ADMIN TO ROLE SYSADMIN;

-- Let the person running setup use the admin role directly.
SET me = CURRENT_USER();
GRANT ROLE GRIDIRON_ADMIN TO USER IDENTIFIER($me);

CREATE DATABASE IF NOT EXISTS GRIDIRON COMMENT = 'NFL fourth-down analytics';
GRANT OWNERSHIP ON DATABASE GRIDIRON TO ROLE GRIDIRON_ADMIN COPY CURRENT GRANTS;

USE ROLE GRIDIRON_ADMIN;
USE DATABASE GRIDIRON;
CREATE SCHEMA IF NOT EXISTS ICEBERG_RAW;
CREATE SCHEMA IF NOT EXISTS ICEBERG;
CREATE SCHEMA IF NOT EXISTS SYNCED;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS MARTS;
CREATE SCHEMA IF NOT EXISTS APP;

USE ROLE ACCOUNTADMIN;

-- Warehouse usage
GRANT USAGE ON WAREHOUSE GRIDIRON_WH TO ROLE GRIDIRON_READER;
GRANT USAGE ON WAREHOUSE GRIDIRON_WH TO ROLE GRIDIRON_LOADER;
GRANT OPERATE, USAGE ON WAREHOUSE GRIDIRON_WH TO ROLE GRIDIRON_ADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE GRIDIRON_ADMIN;

GRANT USAGE ON DATABASE GRIDIRON TO ROLE GRIDIRON_READER;
GRANT USAGE ON DATABASE GRIDIRON TO ROLE GRIDIRON_LOADER;

-- Loader: SYNCED only. CREATE TABLE is needed for the session-scoped staging table.
GRANT USAGE, CREATE TABLE ON SCHEMA GRIDIRON.SYNCED TO ROLE GRIDIRON_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA GRIDIRON.SYNCED
  TO ROLE GRIDIRON_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA GRIDIRON.SYNCED
  TO ROLE GRIDIRON_LOADER;

-- Transformer (dbt): read both source schemas, build STAGING and MARTS.
GRANT USAGE ON SCHEMA GRIDIRON.ICEBERG TO ROLE GRIDIRON_TRANSFORMER;
GRANT SELECT ON ALL VIEWS IN SCHEMA GRIDIRON.ICEBERG TO ROLE GRIDIRON_TRANSFORMER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GRIDIRON.ICEBERG TO ROLE GRIDIRON_TRANSFORMER;
GRANT USAGE ON SCHEMA GRIDIRON.SYNCED TO ROLE GRIDIRON_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA GRIDIRON.SYNCED TO ROLE GRIDIRON_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GRIDIRON.SYNCED TO ROLE GRIDIRON_TRANSFORMER;
GRANT USAGE, CREATE VIEW, CREATE TABLE ON SCHEMA GRIDIRON.STAGING TO ROLE GRIDIRON_TRANSFORMER;
GRANT USAGE, CREATE VIEW, CREATE TABLE ON SCHEMA GRIDIRON.MARTS TO ROLE GRIDIRON_TRANSFORMER;

-- Reader: marts and the app schema only.
GRANT USAGE ON SCHEMA GRIDIRON.MARTS TO ROLE GRIDIRON_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GRIDIRON.MARTS TO ROLE GRIDIRON_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GRIDIRON.MARTS TO ROLE GRIDIRON_READER;
GRANT USAGE ON SCHEMA GRIDIRON.STAGING TO ROLE GRIDIRON_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GRIDIRON.STAGING TO ROLE GRIDIRON_READER;
GRANT USAGE ON SCHEMA GRIDIRON.APP TO ROLE GRIDIRON_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GRIDIRON.APP TO ROLE GRIDIRON_READER;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA GRIDIRON.APP TO ROLE GRIDIRON_READER;

-- Service user for the fallback sync, using key-pair authentication.
-- Generate a key pair locally (see README) and paste the public key body below.
CREATE USER IF NOT EXISTS GRIDIRON_SYNC
  TYPE = SERVICE
  DEFAULT_ROLE = GRIDIRON_LOADER
  DEFAULT_WAREHOUSE = GRIDIRON_WH
  COMMENT = 'Databricks -> Snowflake fallback sync';
-- ALTER USER GRIDIRON_SYNC SET RSA_PUBLIC_KEY = '<PUBLIC_KEY_BODY>';
GRANT ROLE GRIDIRON_LOADER TO USER GRIDIRON_SYNC;
