-- 02_database_and_roles.sql
-- Run as ACCOUNTADMIN (or split between SYSADMIN for objects and SECURITYADMIN for grants).
--
-- Schemas
--   SYNCED       native tables loaded by scripts/sync_to_snowflake.py (the working path
--                with Databricks Free Edition)
--   ICEBERG_RAW  Iceberg tables read through Unity Catalog (needs external storage)
--   ICEBERG      upper-case views over ICEBERG_RAW
--   STAGING      dbt staging views
--   MARTS        dbt marts
--   APP          FANTASY_POINTS UDF and its code stage, projection results maintained by a
--                stream and task, Streamlit app
--
-- Roles (least privilege; each role gets only what its workload needs)
--   GRIDIRON_ADMIN        owns the database and runs the setup scripts
--   GRIDIRON_LOADER       sync: writes SYNCED only
--   GRIDIRON_TRANSFORMER  dbt: reads ICEBERG / SYNCED, builds STAGING and MARTS
--   GRIDIRON_APP_OWNER    owns the Streamlit app, whose queries run with its rights: reads
--                         MARTS and calls APP.FANTASY_POINTS, nothing else
--   GRIDIRON_READER       viewers of the app and analysts: reads MARTS and APP
--
-- Idempotent: safe to run again on an existing deployment. The REVOKE statements remove
-- grants that earlier versions of this script made (they are no-ops otherwise).

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS GRIDIRON_ADMIN;
CREATE ROLE IF NOT EXISTS GRIDIRON_LOADER;
CREATE ROLE IF NOT EXISTS GRIDIRON_TRANSFORMER;
CREATE ROLE IF NOT EXISTS GRIDIRON_READER;
CREATE ROLE IF NOT EXISTS GRIDIRON_APP_OWNER;

GRANT ROLE GRIDIRON_READER TO ROLE GRIDIRON_TRANSFORMER;
GRANT ROLE GRIDIRON_TRANSFORMER TO ROLE GRIDIRON_ADMIN;
GRANT ROLE GRIDIRON_LOADER TO ROLE GRIDIRON_ADMIN;
GRANT ROLE GRIDIRON_APP_OWNER TO ROLE GRIDIRON_ADMIN;
GRANT ROLE GRIDIRON_ADMIN TO ROLE SYSADMIN;

-- Let the person running setup use the admin role directly, and the app owner role to
-- create the app (snowflake/streamlit/01_create_streamlit.sql).
SET me = CURRENT_USER();
GRANT ROLE GRIDIRON_ADMIN TO USER IDENTIFIER($me);
GRANT ROLE GRIDIRON_APP_OWNER TO USER IDENTIFIER($me);

CREATE DATABASE IF NOT EXISTS GRIDIRON COMMENT = 'Fantasy football projections and cheat sheet';
ALTER DATABASE GRIDIRON SET COMMENT = 'Fantasy football projections and cheat sheet';
GRANT OWNERSHIP ON DATABASE GRIDIRON TO ROLE GRIDIRON_ADMIN COPY CURRENT GRANTS;

USE ROLE GRIDIRON_ADMIN;
USE DATABASE GRIDIRON;
CREATE SCHEMA IF NOT EXISTS ICEBERG_RAW;
CREATE SCHEMA IF NOT EXISTS ICEBERG;
CREATE SCHEMA IF NOT EXISTS SYNCED;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS MARTS;
CREATE SCHEMA IF NOT EXISTS APP;

USE ROLE ACCOUNTADMIN;

-- Warehouse usage
GRANT USAGE ON WAREHOUSE GRIDIRON_WH TO ROLE GRIDIRON_READER;
GRANT USAGE ON WAREHOUSE GRIDIRON_WH TO ROLE GRIDIRON_LOADER;
GRANT USAGE ON WAREHOUSE GRIDIRON_WH TO ROLE GRIDIRON_APP_OWNER;
GRANT OPERATE, USAGE ON WAREHOUSE GRIDIRON_WH TO ROLE GRIDIRON_ADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE GRIDIRON_ADMIN;

GRANT USAGE ON DATABASE GRIDIRON TO ROLE GRIDIRON_READER;
GRANT USAGE ON DATABASE GRIDIRON TO ROLE GRIDIRON_LOADER;
GRANT USAGE ON DATABASE GRIDIRON TO ROLE GRIDIRON_APP_OWNER;

-- Loader: SYNCED only. CREATE TABLE is needed for the session-scoped staging table and
-- CREATE STAGE for the temporary stage write_pandas uploads the rows through.
GRANT USAGE, CREATE TABLE, CREATE STAGE ON SCHEMA GRIDIRON.SYNCED TO ROLE GRIDIRON_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA GRIDIRON.SYNCED
  TO ROLE GRIDIRON_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA GRIDIRON.SYNCED
  TO ROLE GRIDIRON_LOADER;

-- Transformer (dbt): read both source schemas, build STAGING and MARTS.
GRANT USAGE ON SCHEMA GRIDIRON.ICEBERG TO ROLE GRIDIRON_TRANSFORMER;
GRANT SELECT ON ALL VIEWS IN SCHEMA GRIDIRON.ICEBERG TO ROLE GRIDIRON_TRANSFORMER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GRIDIRON.ICEBERG TO ROLE GRIDIRON_TRANSFORMER;
GRANT USAGE ON SCHEMA GRIDIRON.SYNCED TO ROLE GRIDIRON_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA GRIDIRON.SYNCED TO ROLE GRIDIRON_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GRIDIRON.SYNCED TO ROLE GRIDIRON_TRANSFORMER;
GRANT USAGE, CREATE VIEW, CREATE TABLE ON SCHEMA GRIDIRON.STAGING TO ROLE GRIDIRON_TRANSFORMER;
GRANT USAGE, CREATE VIEW, CREATE TABLE ON SCHEMA GRIDIRON.MARTS TO ROLE GRIDIRON_TRANSFORMER;

-- Reader: marts and the app schema only.
GRANT USAGE ON SCHEMA GRIDIRON.MARTS TO ROLE GRIDIRON_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GRIDIRON.MARTS TO ROLE GRIDIRON_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GRIDIRON.MARTS TO ROLE GRIDIRON_READER;
REVOKE SELECT ON FUTURE VIEWS IN SCHEMA GRIDIRON.STAGING FROM ROLE GRIDIRON_READER;
REVOKE SELECT ON ALL VIEWS IN SCHEMA GRIDIRON.STAGING FROM ROLE GRIDIRON_READER;
REVOKE USAGE ON SCHEMA GRIDIRON.STAGING FROM ROLE GRIDIRON_READER;
GRANT USAGE ON SCHEMA GRIDIRON.APP TO ROLE GRIDIRON_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GRIDIRON.APP TO ROLE GRIDIRON_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GRIDIRON.APP TO ROLE GRIDIRON_READER;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA GRIDIRON.APP TO ROLE GRIDIRON_READER;

-- App owner: reads the marts, creates the app in APP. USAGE on APP.FANTASY_POINTS is
-- granted in snowflake/snowpark/01_create_udf.sql, right after the function is created.
GRANT USAGE ON SCHEMA GRIDIRON.MARTS TO ROLE GRIDIRON_APP_OWNER;
GRANT SELECT ON ALL TABLES IN SCHEMA GRIDIRON.MARTS TO ROLE GRIDIRON_APP_OWNER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GRIDIRON.MARTS TO ROLE GRIDIRON_APP_OWNER;
GRANT SELECT ON ALL VIEWS IN SCHEMA GRIDIRON.MARTS TO ROLE GRIDIRON_APP_OWNER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GRIDIRON.MARTS TO ROLE GRIDIRON_APP_OWNER;
GRANT USAGE, CREATE STREAMLIT ON SCHEMA GRIDIRON.APP TO ROLE GRIDIRON_APP_OWNER;

-- Service users for the sync and for dbt. Service users cannot log in with a password;
-- each gets its own key pair. Generate the keys locally and set each public key with the
-- commented ALTER USER statements (steps in docs/deploy.md, "Key pairs").
CREATE USER IF NOT EXISTS GRIDIRON_SYNC
  TYPE = SERVICE
  DEFAULT_ROLE = GRIDIRON_LOADER
  DEFAULT_WAREHOUSE = GRIDIRON_WH
  COMMENT = 'Databricks -> Snowflake sync of the serving tables';
-- ALTER USER GRIDIRON_SYNC SET RSA_PUBLIC_KEY = '<PUBLIC_KEY_BODY>';
GRANT ROLE GRIDIRON_LOADER TO USER GRIDIRON_SYNC;

CREATE USER IF NOT EXISTS GRIDIRON_DBT
  TYPE = SERVICE
  DEFAULT_ROLE = GRIDIRON_TRANSFORMER
  DEFAULT_WAREHOUSE = GRIDIRON_WH
  COMMENT = 'dbt builds of STAGING and MARTS';
-- ALTER USER GRIDIRON_DBT SET RSA_PUBLIC_KEY = '<PUBLIC_KEY_BODY>';
GRANT ROLE GRIDIRON_TRANSFORMER TO USER GRIDIRON_DBT;
