-- Generated by scripts/generate_snowflake_sql.py from the gold table schemas.
-- Do not edit by hand.
-- Upper-case views over the Iceberg tables so downstream SQL does not
-- depend on Unity Catalog's lower-case identifiers.

USE ROLE GRIDIRON_ADMIN;
USE DATABASE GRIDIRON;
USE WAREHOUSE GRIDIRON_WH;

CREATE OR REPLACE VIEW ICEBERG.FOURTH_DOWN_DECISIONS AS
SELECT
    "game_id" AS GAME_ID,
    "play_id" AS PLAY_ID,
    "season" AS SEASON,
    "season_type" AS SEASON_TYPE,
    "week" AS WEEK,
    "game_date" AS GAME_DATE,
    "posteam" AS POSTEAM,
    "defteam" AS DEFTEAM,
    "coach" AS COACH,
    "posteam_type" AS POSTEAM_TYPE,
    "qtr" AS QTR,
    "ydstogo" AS YDSTOGO,
    "yardline_100" AS YARDLINE_100,
    "game_seconds_remaining" AS GAME_SECONDS_REMAINING,
    "score_differential" AS SCORE_DIFFERENTIAL,
    "posteam_timeouts_remaining" AS POSTEAM_TIMEOUTS_REMAINING,
    "wp" AS WP,
    "ep" AS EP,
    "epa" AS EPA,
    "wpa" AS WPA,
    "kick_distance" AS KICK_DISTANCE,
    "return_yards" AS RETURN_YARDS,
    "touchback" AS TOUCHBACK,
    "decision" AS DECISION,
    "outcome" AS OUTCOME,
    "converted" AS CONVERTED
FROM ICEBERG_RAW.FOURTH_DOWN_DECISIONS;

CREATE OR REPLACE VIEW ICEBERG.FOURTH_DOWN_SCORED AS
SELECT
    "game_id" AS GAME_ID,
    "play_id" AS PLAY_ID,
    "season" AS SEASON,
    "season_type" AS SEASON_TYPE,
    "week" AS WEEK,
    "game_date" AS GAME_DATE,
    "posteam" AS POSTEAM,
    "defteam" AS DEFTEAM,
    "coach" AS COACH,
    "posteam_type" AS POSTEAM_TYPE,
    "qtr" AS QTR,
    "ydstogo" AS YDSTOGO,
    "yardline_100" AS YARDLINE_100,
    "game_seconds_remaining" AS GAME_SECONDS_REMAINING,
    "score_differential" AS SCORE_DIFFERENTIAL,
    "posteam_timeouts_remaining" AS POSTEAM_TIMEOUTS_REMAINING,
    "wp" AS WP,
    "ep" AS EP,
    "epa" AS EPA,
    "wpa" AS WPA,
    "kick_distance" AS KICK_DISTANCE,
    "return_yards" AS RETURN_YARDS,
    "touchback" AS TOUCHBACK,
    "decision" AS DECISION,
    "outcome" AS OUTCOME,
    "converted" AS CONVERTED,
    "p_convert" AS P_CONVERT,
    "p_field_goal" AS P_FIELD_GOAL,
    "ev_go" AS EV_GO,
    "ev_punt" AS EV_PUNT,
    "ev_field_goal" AS EV_FIELD_GOAL,
    "recommendation" AS RECOMMENDATION,
    "go_advantage" AS GO_ADVANTAGE,
    "expected_points_lost" AS EXPECTED_POINTS_LOST,
    "followed_model" AS FOLLOWED_MODEL,
    "is_neutral_situation" AS IS_NEUTRAL_SITUATION
FROM ICEBERG_RAW.FOURTH_DOWN_SCORED;

CREATE OR REPLACE VIEW ICEBERG.TEAM_SEASON_SUMMARY AS
SELECT
    "season" AS SEASON,
    "team" AS TEAM,
    "offensive_plays" AS OFFENSIVE_PLAYS,
    "epa_per_play" AS EPA_PER_PLAY,
    "success_rate" AS SUCCESS_RATE,
    "fourth_downs" AS FOURTH_DOWNS,
    "go_attempts" AS GO_ATTEMPTS,
    "go_conversions" AS GO_CONVERSIONS,
    "punts" AS PUNTS,
    "field_goal_attempts" AS FIELD_GOAL_ATTEMPTS,
    "go_rate" AS GO_RATE,
    "conversion_rate" AS CONVERSION_RATE
FROM ICEBERG_RAW.TEAM_SEASON_SUMMARY;

CREATE OR REPLACE VIEW ICEBERG.GAME_SUMMARY AS
SELECT
    "game_id" AS GAME_ID,
    "season" AS SEASON,
    "season_type" AS SEASON_TYPE,
    "week" AS WEEK,
    "game_date" AS GAME_DATE,
    "home_team" AS HOME_TEAM,
    "away_team" AS AWAY_TEAM,
    "home_coach" AS HOME_COACH,
    "away_coach" AS AWAY_COACH,
    "home_score" AS HOME_SCORE,
    "away_score" AS AWAY_SCORE,
    "scrimmage_plays" AS SCRIMMAGE_PLAYS,
    "home_fourth_downs" AS HOME_FOURTH_DOWNS,
    "home_go_attempts" AS HOME_GO_ATTEMPTS,
    "away_fourth_downs" AS AWAY_FOURTH_DOWNS,
    "away_go_attempts" AS AWAY_GO_ATTEMPTS,
    "winner" AS WINNER
FROM ICEBERG_RAW.GAME_SUMMARY;

CREATE OR REPLACE VIEW ICEBERG.COACH_AGGRESSIVENESS AS
SELECT
    "season" AS SEASON,
    "team" AS TEAM,
    "coach" AS COACH,
    "neutral_fourth_downs" AS NEUTRAL_FOURTH_DOWNS,
    "go_attempts" AS GO_ATTEMPTS,
    "go_recommendations" AS GO_RECOMMENDATIONS,
    "went_for_it_when_recommended" AS WENT_FOR_IT_WHEN_RECOMMENDED,
    "expected_points_lost" AS EXPECTED_POINTS_LOST,
    "avg_missed_go_advantage" AS AVG_MISSED_GO_ADVANTAGE,
    "go_rate" AS GO_RATE,
    "go_rate_when_recommended" AS GO_RATE_WHEN_RECOMMENDED,
    "expected_points_lost_per_fourth_down" AS EXPECTED_POINTS_LOST_PER_FOURTH_DOWN,
    "aggressiveness_rank" AS AGGRESSIVENESS_RANK
FROM ICEBERG_RAW.COACH_AGGRESSIVENESS;
