"""Generate Snowflake DDL for the serving tables from the gold table schemas.

The gold fixture Parquet files are produced by the real pipeline and model code, so their
Arrow schemas are the contract (a test checks the code still produces them). Regenerate
after changing a serving table:

    python scripts/generate_snowflake_sql.py          # write files
    python scripts/generate_snowflake_sql.py --check  # fail if files are stale (CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pyarrow.parquet as pq

from gridiron.serving import SERVING_TABLES
from gridiron.snowflake_sql import create_table_sql, iceberg_table_sql, iceberg_view_sql

ROOT = Path(__file__).resolve().parent.parent
GOLD = ROOT / "tests" / "fixtures" / "gold"
HEADER = "-- Generated by scripts/generate_snowflake_sql.py from the gold table schemas.\n"
HEADER += "-- Do not edit by hand.\n"


def render() -> dict[Path, str]:
    schemas = {t: pq.read_schema(GOLD / f"{t}.parquet") for t in SERVING_TABLES}
    views = "\n\n".join(
        iceberg_view_sql("ICEBERG", "ICEBERG_RAW", t, s) for t, s in schemas.items()
    )
    tables = "\n\n".join(create_table_sql("SYNCED", t, s) for t, s in schemas.items())
    iceberg = "\n\n".join(
        iceberg_table_sql("ICEBERG_RAW", t, "GRIDIRON_UNITY_CATALOG") for t in schemas
    )
    context = "USE ROLE GRIDIRON_ADMIN;\nUSE DATABASE GRIDIRON;\nUSE WAREHOUSE GRIDIRON_WH;\n"
    return {
        ROOT / "snowflake" / "iceberg" / "02_iceberg_tables.sql": (
            f"{HEADER}-- Iceberg path only (needs external storage; see the README):\n"
            f"-- externally managed Iceberg tables over the Unity Catalog serving tables.\n"
            f"-- Databricks stays the only writer; AUTO_REFRESH polls the catalog for\n"
            f"-- new snapshots. Run as GRIDIRON_ADMIN after 01_catalog_integration.sql.\n\n"
            f"{context}\n{iceberg}\n"
        ),
        ROOT / "snowflake" / "iceberg" / "03_iceberg_views.sql": (
            f"{HEADER}-- Iceberg path only: upper-case views over the Iceberg tables, so dbt\n"
            f"-- reads the same column names as on the synced path.\n\n{context}\n{views}\n"
        ),
        ROOT / "snowflake" / "sync" / "01_synced_tables.sql": (
            f"{HEADER}-- Native tables loaded by scripts/sync_to_snowflake.py (the production\n"
            f"-- path with Databricks Free Edition; see the README).\n"
            f"-- Primary keys are informational in Snowflake; the sync MERGE enforces them.\n\n"
            f"{context}\n{tables}\n"
        ),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    stale = []
    for path, content in render().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("stale generated SQL:", *[str(p.relative_to(ROOT)) for p in stale], sep="\n  ")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
