"""Generate Snowflake DDL for the serving tables from the gold table schemas.

The gold fixture parquet files are produced by the real transformations, so their Arrow
schemas are the contract. Regenerate after changing a gold table:

    python scripts/generate_snowflake_sql.py          # write files
    python scripts/generate_snowflake_sql.py --check  # fail if files are stale (CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pyarrow.parquet as pq

from gridiron.serving import SERVING_TABLES
from gridiron.snowflake_sql import create_table_sql, iceberg_view_sql

ROOT = Path(__file__).resolve().parent.parent
GOLD = ROOT / "tests" / "fixtures" / "gold"
HEADER = "-- Generated by scripts/generate_snowflake_sql.py from the gold table schemas.\n"
HEADER += "-- Do not edit by hand.\n"


def render() -> dict[Path, str]:
    schemas = {t: pq.read_schema(GOLD / f"{t}.parquet") for t in SERVING_TABLES}
    views = "\n\n".join(
        iceberg_view_sql("ICEBERG", "ICEBERG_RAW", t, s) for t, s in schemas.items()
    )
    tables = "\n\n".join(create_table_sql("SYNCED", t, s) for t, s in schemas.items())
    context = "USE ROLE GRIDIRON_ADMIN;\nUSE DATABASE GRIDIRON;\nUSE WAREHOUSE GRIDIRON_WH;\n"
    return {
        ROOT / "snowflake" / "iceberg" / "03_iceberg_views.sql": (
            f"{HEADER}-- Upper-case views over the Iceberg tables so downstream SQL does not\n"
            f"-- depend on Unity Catalog's lower-case identifiers.\n\n{context}\n{views}\n"
        ),
        ROOT / "snowflake" / "sync" / "01_synced_tables.sql": (
            f"{HEADER}-- Native tables loaded by scripts/sync_to_snowflake.py (fallback path).\n"
            f"-- Primary keys are informational in Snowflake; the sync MERGE enforces them.\n\n"
            f"{context}\n{tables}\n"
        ),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    stale = []
    for path, content in render().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("stale generated SQL:", *[str(p.relative_to(ROOT)) for p in stale], sep="\n  ")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
